disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - explicit_init
  - first_where
  - modifier_order
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - Pods
  - Examples

reporter: "xcode"
