name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      render: swift

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options:
        - iOS
        - macOS
        - tvOS
        - visionOS
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
    validations:
      required: true
